# Generated by Django 2.0.6 on 2018-06-25 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=2)),
                ('fecha', models.SmallIntegerField()),
                ('horario', models.DateTimeField()),
                ('goles1', models.SmallIntegerField(blank=True, null=True)),
                ('goles2', models.SmallIntegerField(blank=True, null=True)),
                ('equipo1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipo1', to='app.Equipo')),
                ('equipo2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipo2', to='app.Equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Prediccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goles1', models.SmallIntegerField()),
                ('goles2', models.SmallIntegerField()),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partido', to='app.Partido')),
            ],
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='prediccion',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torneo', to='app.Torneo'),
        ),
        migrations.AddField(
            model_name='prediccion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partido',
            name='torneo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Torneo'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='torneos',
            field=models.ManyToManyField(to='app.Torneo'),
        ),
    ]
