# Generated by Django 2.0.6 on 2018-07-05 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=10)),
                ('fecha', models.SmallIntegerField()),
                ('horario', models.DateTimeField()),
                ('goles1', models.SmallIntegerField(blank=True, null=True)),
                ('goles2', models.SmallIntegerField(blank=True, null=True)),
                ('eliminatoria', models.BooleanField(default=False)),
                ('fase_eliminatoria', models.SmallIntegerField(blank=True, null=True)),
                ('penales1', models.SmallIntegerField(blank=True, null=True)),
                ('penales2', models.SmallIntegerField(blank=True, null=True)),
                ('equipo1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo1', to='app.Equipo')),
                ('equipo2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo2', to='app.Equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Prediccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goles1', models.SmallIntegerField()),
                ('goles2', models.SmallIntegerField()),
                ('ganador', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipo_ganador', to='app.Equipo')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partido', to='app.Partido')),
            ],
        ),
        migrations.CreateModel(
            name='Puntaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plenos', models.SmallIntegerField(default=0)),
                ('resultados', models.SmallIntegerField(default=0)),
                ('penales', models.SmallIntegerField(default=0)),
                ('error_clasificado', models.SmallIntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='prediccion',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torneo', to='app.Torneo'),
        ),
        migrations.AddField(
            model_name='prediccion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partido',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Torneo'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='torneos',
            field=models.ManyToManyField(to='app.Torneo'),
        ),
    ]
