# Generated by Django 2.0.6 on 2018-07-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediccion',
            name='hola',
            field=models.SmallIntegerField(default=0),
        ),
    ]
