# Generated by Django 2.0.6 on 2018-06-25 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediccion',
            name='torneo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='torneo', to='app.Torneo'),
        ),
    ]
