# Generated by Django 2.0.6 on 2018-06-25 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180625_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediccion',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torneo', to='app.Torneo'),
        ),
    ]
