# Generated by Django 2.0.6 on 2018-07-05 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_prediccion_hola'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prediccion',
            name='hola',
        ),
    ]
