# Generated by Django 2.0.6 on 2018-07-05 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_prediccion_hola'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediccion',
            name='ganador',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipo_gan', to='app.Equipo'),
        ),
    ]
