# Generated by Django 2.0.6 on 2018-06-26 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180625_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='grupo',
            field=models.CharField(max_length=10),
        ),
    ]
