# Generated by Django 2.0.6 on 2018-06-27 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20180625_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plenos', models.SmallIntegerField(default=0)),
                ('resultados', models.SmallIntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='goles1',
            field=models.SmallIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='goles2',
            field=models.SmallIntegerField(default=-1),
        ),
    ]
