# Generated by Django 2.0.6 on 2018-06-27 00:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_auto_20180626_2153'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resultados',
            new_name='Puntajes',
        ),
    ]
