# Generated by Django 2.0.6 on 2018-06-27 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180626_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntaje',
            name='puntos',
            field=models.SmallIntegerField(default=0),
        ),
    ]
