# Generated by Django 2.0.6 on 2018-06-27 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_puntaje_puntos'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='prediccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prediccion', to='app.Prediccion'),
        ),
    ]
