# Generated by Django 2.0.6 on 2018-06-27 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_partido_prediccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='equipo1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo1', to='app.Equipo'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='equipo2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo2', to='app.Equipo'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Torneo'),
        ),
    ]
