# Generated by Django 2.0.6 on 2018-06-28 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180627_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediccion',
            name='goles1',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='goles2',
            field=models.SmallIntegerField(),
        ),
    ]
