# Generated by Django 2.0.6 on 2018-06-29 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_puntaje_puntos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partido',
            name='prediccion',
        ),
    ]
