# Generated by Django 2.0.6 on 2018-06-30 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_prediccion_clasifica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediccion',
            name='clasifica',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Equipo_clasifica', to='app.Equipo'),
        ),
    ]
