# Generated by Django 2.0.6 on 2018-06-30 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20180629_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='ganador',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ganador', to='app.Equipo'),
        ),
        migrations.AddField(
            model_name='puntaje',
            name='error_clasificado',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='puntaje',
            name='penales',
            field=models.SmallIntegerField(default=0),
        ),
    ]
