# Generated by Django 2.0.6 on 2018-06-30 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20180630_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediccion',
            name='clasifica',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Equipo_clasifica', to='app.Equipo'),
        ),
    ]
