# Generated by Django 2.0.6 on 2018-07-02 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20180630_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prediccion',
            name='clasifica',
        ),
        migrations.AddField(
            model_name='partido',
            name='eliminatoria',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partido',
            name='penales1',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='penales2',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prediccion',
            name='ganador',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipo_ganador', to='app.Equipo'),
        ),
    ]
