# Generated by Django 2.0.6 on 2018-07-02 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20180701_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='ganador',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ganador', to='app.Equipo'),
        ),
    ]
