# Generated by Django 2.0.6 on 2018-07-02 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20180701_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partido',
            name='ganador',
        ),
    ]
