# Generated by Django 2.0.6 on 2018-07-02 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_partido_ganador'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='fase_eliminatoria',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='prediccion',
            name='ganador',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipo_ganador', to='app.Equipo'),
        ),
    ]
