# Generated by Django 2.0.6 on 2018-07-05 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180705_1336'),
        ('app', '0022_auto_20180702_1825'),
    ]

    operations = [
    ]
